// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: admin_service.proto

package certv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyRequest_PatternType int32

const (
	PolicyRequest_EXACT    PolicyRequest_PatternType = 0
	PolicyRequest_WILDCARD PolicyRequest_PatternType = 1
	PolicyRequest_REGEX    PolicyRequest_PatternType = 2
)

// Enum value maps for PolicyRequest_PatternType.
var (
	PolicyRequest_PatternType_name = map[int32]string{
		0: "EXACT",
		1: "WILDCARD",
		2: "REGEX",
	}
	PolicyRequest_PatternType_value = map[string]int32{
		"EXACT":    0,
		"WILDCARD": 1,
		"REGEX":    2,
	}
)

func (x PolicyRequest_PatternType) Enum() *PolicyRequest_PatternType {
	p := new(PolicyRequest_PatternType)
	*p = x
	return p
}

func (x PolicyRequest_PatternType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyRequest_PatternType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_service_proto_enumTypes[0].Descriptor()
}

func (PolicyRequest_PatternType) Type() protoreflect.EnumType {
	return &file_admin_service_proto_enumTypes[0]
}

func (x PolicyRequest_PatternType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyRequest_PatternType.Descriptor instead.
func (PolicyRequest_PatternType) EnumDescriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0, 0}
}

type PolicyRequest_Action int32

const (
	PolicyRequest_ALLOW PolicyRequest_Action = 0
	PolicyRequest_BLOCK PolicyRequest_Action = 1
)

// Enum value maps for PolicyRequest_Action.
var (
	PolicyRequest_Action_name = map[int32]string{
		0: "ALLOW",
		1: "BLOCK",
	}
	PolicyRequest_Action_value = map[string]int32{
		"ALLOW": 0,
		"BLOCK": 1,
	}
)

func (x PolicyRequest_Action) Enum() *PolicyRequest_Action {
	p := new(PolicyRequest_Action)
	*p = x
	return p
}

func (x PolicyRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_service_proto_enumTypes[1].Descriptor()
}

func (PolicyRequest_Action) Type() protoreflect.EnumType {
	return &file_admin_service_proto_enumTypes[1]
}

func (x PolicyRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyRequest_Action.Descriptor instead.
func (PolicyRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0, 1}
}

type PolicyRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	IssuerId      string                    `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	DomainPattern string                    `protobuf:"bytes,2,opt,name=domain_pattern,json=domainPattern,proto3" json:"domain_pattern,omitempty"`
	PatternType   PolicyRequest_PatternType `protobuf:"varint,3,opt,name=pattern_type,json=patternType,proto3,enum=cert_issuer.v1.PolicyRequest_PatternType" json:"pattern_type,omitempty"`
	Action        PolicyRequest_Action      `protobuf:"varint,4,opt,name=action,proto3,enum=cert_issuer.v1.PolicyRequest_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *PolicyRequest) GetDomainPattern() string {
	if x != nil {
		return x.DomainPattern
	}
	return ""
}

func (x *PolicyRequest) GetPatternType() PolicyRequest_PatternType {
	if x != nil {
		return x.PatternType
	}
	return PolicyRequest_EXACT
}

func (x *PolicyRequest) GetAction() PolicyRequest_Action {
	if x != nil {
		return x.Action
	}
	return PolicyRequest_ALLOW
}

type PolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyResponse) Reset() {
	*x = PolicyResponse{}
	mi := &file_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResponse) ProtoMessage() {}

func (x *PolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResponse.ProtoReflect.Descriptor instead.
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

type MetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalCertificates int32                  `protobuf:"varint,1,opt,name=total_certificates,json=totalCertificates,proto3" json:"total_certificates,omitempty"`
	ExpiringSoon      int32                  `protobuf:"varint,2,opt,name=expiring_soon,json=expiringSoon,proto3" json:"expiring_soon,omitempty"`
	QueueDepth        int32                  `protobuf:"varint,3,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	RateLimitUsage    float32                `protobuf:"fixed32,4,opt,name=rate_limit_usage,json=rateLimitUsage,proto3" json:"rate_limit_usage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsResponse) GetTotalCertificates() int32 {
	if x != nil {
		return x.TotalCertificates
	}
	return 0
}

func (x *MetricsResponse) GetExpiringSoon() int32 {
	if x != nil {
		return x.ExpiringSoon
	}
	return 0
}

func (x *MetricsResponse) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *MetricsResponse) GetRateLimitUsage() float32 {
	if x != nil {
		return x.RateLimitUsage
	}
	return 0
}

var File_admin_service_proto protoreflect.FileDescriptor

const file_admin_service_proto_rawDesc = "" +
	"\n" +
	"\x13admin_service.proto\x12\x0ecert_issuer.v1\"\xb2\x02\n" +
	"\rPolicyRequest\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12%\n" +
	"\x0edomain_pattern\x18\x02 \x01(\tR\rdomainPattern\x12L\n" +
	"\fpattern_type\x18\x03 \x01(\x0e2).cert_issuer.v1.PolicyRequest.PatternTypeR\vpatternType\x12<\n" +
	"\x06action\x18\x04 \x01(\x0e2$.cert_issuer.v1.PolicyRequest.ActionR\x06action\"1\n" +
	"\vPatternType\x12\t\n" +
	"\x05EXACT\x10\x00\x12\f\n" +
	"\bWILDCARD\x10\x01\x12\t\n" +
	"\x05REGEX\x10\x02\"\x1e\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\t\n" +
	"\x05BLOCK\x10\x01\"D\n" +
	"\x0ePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x0eMetricsRequest\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\"\xb0\x01\n" +
	"\x0fMetricsResponse\x12-\n" +
	"\x12total_certificates\x18\x01 \x01(\x05R\x11totalCertificates\x12#\n" +
	"\rexpiring_soon\x18\x02 \x01(\x05R\fexpiringSoon\x12\x1f\n" +
	"\vqueue_depth\x18\x03 \x01(\x05R\n" +
	"queueDepth\x12(\n" +
	"\x10rate_limit_usage\x18\x04 \x01(\x02R\x0erateLimitUsage2\xac\x01\n" +
	"\fAdminService\x12M\n" +
	"\fManagePolicy\x12\x1d.cert_issuer.v1.PolicyRequest\x1a\x1e.cert_issuer.v1.PolicyResponse\x12M\n" +
	"\n" +
	"GetMetrics\x12\x1e.cert_issuer.v1.MetricsRequest\x1a\x1f.cert_issuer.v1.MetricsResponseB?Z=github.com/mdv-pochta/cert-system/proto/cert_issuer/v1;certv1b\x06proto3"

var (
	file_admin_service_proto_rawDescOnce sync.Once
	file_admin_service_proto_rawDescData []byte
)

func file_admin_service_proto_rawDescGZIP() []byte {
	file_admin_service_proto_rawDescOnce.Do(func() {
		file_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_service_proto_rawDesc), len(file_admin_service_proto_rawDesc)))
	})
	return file_admin_service_proto_rawDescData
}

var file_admin_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_service_proto_goTypes = []any{
	(PolicyRequest_PatternType)(0), // 0: cert_issuer.v1.PolicyRequest.PatternType
	(PolicyRequest_Action)(0),      // 1: cert_issuer.v1.PolicyRequest.Action
	(*PolicyRequest)(nil),          // 2: cert_issuer.v1.PolicyRequest
	(*PolicyResponse)(nil),         // 3: cert_issuer.v1.PolicyResponse
	(*MetricsRequest)(nil),         // 4: cert_issuer.v1.MetricsRequest
	(*MetricsResponse)(nil),        // 5: cert_issuer.v1.MetricsResponse
}
var file_admin_service_proto_depIdxs = []int32{
	0, // 0: cert_issuer.v1.PolicyRequest.pattern_type:type_name -> cert_issuer.v1.PolicyRequest.PatternType
	1, // 1: cert_issuer.v1.PolicyRequest.action:type_name -> cert_issuer.v1.PolicyRequest.Action
	2, // 2: cert_issuer.v1.AdminService.ManagePolicy:input_type -> cert_issuer.v1.PolicyRequest
	4, // 3: cert_issuer.v1.AdminService.GetMetrics:input_type -> cert_issuer.v1.MetricsRequest
	3, // 4: cert_issuer.v1.AdminService.ManagePolicy:output_type -> cert_issuer.v1.PolicyResponse
	5, // 5: cert_issuer.v1.AdminService.GetMetrics:output_type -> cert_issuer.v1.MetricsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_service_proto_init() }
func file_admin_service_proto_init() {
	if File_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_service_proto_rawDesc), len(file_admin_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_service_proto_goTypes,
		DependencyIndexes: file_admin_service_proto_depIdxs,
		EnumInfos:         file_admin_service_proto_enumTypes,
		MessageInfos:      file_admin_service_proto_msgTypes,
	}.Build()
	File_admin_service_proto = out.File
	file_admin_service_proto_goTypes = nil
	file_admin_service_proto_depIdxs = nil
}
