# .golangci.yml — рекомендованный в 2025
run:
  timeout: 10m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - exportloopref
    - errorlint
    - makezero
    - prealloc
    - wastedassign

issues:
  exclude-use-default: false
