version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - errorlint
    - makezero
    - misspell
    - prealloc
    - revive
    - unconvert
    - wastedassign
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
