// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/cert_issuer/v1/certificate_service.proto

package certv1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateRequest_RequestType int32

const (
	CertificateRequest_NEW     CertificateRequest_RequestType = 0
	CertificateRequest_RENEWAL CertificateRequest_RequestType = 1
)

// Enum value maps for CertificateRequest_RequestType.
var (
	CertificateRequest_RequestType_name = map[int32]string{
		0: "NEW",
		1: "RENEWAL",
	}
	CertificateRequest_RequestType_value = map[string]int32{
		"NEW":     0,
		"RENEWAL": 1,
	}
)

func (x CertificateRequest_RequestType) Enum() *CertificateRequest_RequestType {
	p := new(CertificateRequest_RequestType)
	*p = x
	return p
}

func (x CertificateRequest_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateRequest_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cert_issuer_v1_certificate_service_proto_enumTypes[0].Descriptor()
}

func (CertificateRequest_RequestType) Type() protoreflect.EnumType {
	return &file_proto_cert_issuer_v1_certificate_service_proto_enumTypes[0]
}

func (x CertificateRequest_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateRequest_RequestType.Descriptor instead.
func (CertificateRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{0, 0}
}

type CertificateResponse_Status int32

const (
	CertificateResponse_UNKNOWN    CertificateResponse_Status = 0
	CertificateResponse_PENDING    CertificateResponse_Status = 1
	CertificateResponse_QUEUED     CertificateResponse_Status = 2
	CertificateResponse_PROCESSING CertificateResponse_Status = 3
	CertificateResponse_APPROVED   CertificateResponse_Status = 4
	CertificateResponse_FAILED     CertificateResponse_Status = 5
)

// Enum value maps for CertificateResponse_Status.
var (
	CertificateResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "QUEUED",
		3: "PROCESSING",
		4: "APPROVED",
		5: "FAILED",
	}
	CertificateResponse_Status_value = map[string]int32{
		"UNKNOWN":    0,
		"PENDING":    1,
		"QUEUED":     2,
		"PROCESSING": 3,
		"APPROVED":   4,
		"FAILED":     5,
	}
)

func (x CertificateResponse_Status) Enum() *CertificateResponse_Status {
	p := new(CertificateResponse_Status)
	*p = x
	return p
}

func (x CertificateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cert_issuer_v1_certificate_service_proto_enumTypes[1].Descriptor()
}

func (CertificateResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_cert_issuer_v1_certificate_service_proto_enumTypes[1]
}

func (x CertificateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateResponse_Status.Descriptor instead.
func (CertificateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{1, 0}
}

type StatusResponse_Status int32

const (
	StatusResponse_UNKNOWN  StatusResponse_Status = 0
	StatusResponse_PENDING  StatusResponse_Status = 1
	StatusResponse_APPROVED StatusResponse_Status = 2
	StatusResponse_FAILED   StatusResponse_Status = 3
	StatusResponse_EXPIRED  StatusResponse_Status = 4
)

// Enum value maps for StatusResponse_Status.
var (
	StatusResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "APPROVED",
		3: "FAILED",
		4: "EXPIRED",
	}
	StatusResponse_Status_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"APPROVED": 2,
		"FAILED":   3,
		"EXPIRED":  4,
	}
)

func (x StatusResponse_Status) Enum() *StatusResponse_Status {
	p := new(StatusResponse_Status)
	*p = x
	return p
}

func (x StatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cert_issuer_v1_certificate_service_proto_enumTypes[2].Descriptor()
}

func (StatusResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_cert_issuer_v1_certificate_service_proto_enumTypes[2]
}

func (x StatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_Status.Descriptor instead.
func (StatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{3, 0}
}

type CertificateRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Domain        string                         `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DnsNames      []string                       `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	DurationDays  int32                          `protobuf:"varint,3,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	IssuerId      string                         `protobuf:"bytes,4,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	ClusterName   string                         `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Type          CertificateRequest_RequestType `protobuf:"varint,6,opt,name=type,proto3,enum=cert_issuer.v1.CertificateRequest_RequestType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CertificateRequest) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *CertificateRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CertificateRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *CertificateRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CertificateRequest) GetType() CertificateRequest_RequestType {
	if x != nil {
		return x.Type
	}
	return CertificateRequest_NEW
}

type CertificateResponse struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	RequestId      string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status         CertificateResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=cert_issuer.v1.CertificateResponse_Status" json:"status,omitempty"`
	QueuePosition  int32                      `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	EstimatedReady *timestamp.Timestamp       `protobuf:"bytes,4,opt,name=estimated_ready,json=estimatedReady,proto3" json:"estimated_ready,omitempty"`
	ErrorMessage   string                     `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CertificateResponse) GetStatus() CertificateResponse_Status {
	if x != nil {
		return x.Status
	}
	return CertificateResponse_UNKNOWN
}

func (x *CertificateResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *CertificateResponse) GetEstimatedReady() *timestamp.Timestamp {
	if x != nil {
		return x.EstimatedReady
	}
	return nil
}

func (x *CertificateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           StatusResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=cert_issuer.v1.StatusResponse_Status" json:"status,omitempty"`
	CertificatePem   []byte                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	KeyPem           []byte                 `protobuf:"bytes,3,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	CaPem            []byte                 `protobuf:"bytes,4,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	NotBefore        *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter         *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	DaysUntilRenewal int32                  `protobuf:"varint,7,opt,name=days_until_renewal,json=daysUntilRenewal,proto3" json:"days_until_renewal,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() StatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return StatusResponse_UNKNOWN
}

func (x *StatusResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *StatusResponse) GetKeyPem() []byte {
	if x != nil {
		return x.KeyPem
	}
	return nil
}

func (x *StatusResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *StatusResponse) GetNotBefore() *timestamp.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *StatusResponse) GetNotAfter() *timestamp.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *StatusResponse) GetDaysUntilRenewal() int32 {
	if x != nil {
		return x.DaysUntilRenewal
	}
	return 0
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertificateId string                 `protobuf:"bytes,1,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	IssuerId      string                 `protobuf:"bytes,2,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{4}
}

func (x *RenewRequest) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *RenewRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        StatusResponse_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=cert_issuer.v1.StatusResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cert_issuer_v1_certificate_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP(), []int{5}
}

func (x *RenewResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenewResponse) GetStatus() StatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return StatusResponse_UNKNOWN
}

var File_proto_cert_issuer_v1_certificate_service_proto protoreflect.FileDescriptor

const file_proto_cert_issuer_v1_certificate_service_proto_rawDesc = "" +
	"\n" +
	".proto/cert_issuer/v1/certificate_service.proto\x12\x0ecert_issuer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\x12CertificateRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNames\x12#\n" +
	"\rduration_days\x18\x03 \x01(\x05R\fdurationDays\x12\x1b\n" +
	"\tissuer_id\x18\x04 \x01(\tR\bissuerId\x12!\n" +
	"\fcluster_name\x18\x05 \x01(\tR\vclusterName\x12B\n" +
	"\x04type\x18\x06 \x01(\x0e2..cert_issuer.v1.CertificateRequest.RequestTypeR\x04type\"#\n" +
	"\vRequestType\x12\a\n" +
	"\x03NEW\x10\x00\x12\v\n" +
	"\aRENEWAL\x10\x01\"\xe3\x02\n" +
	"\x13CertificateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12B\n" +
	"\x06status\x18\x02 \x01(\x0e2*.cert_issuer.v1.CertificateResponse.StatusR\x06status\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\x05R\rqueuePosition\x12C\n" +
	"\x0festimated_ready\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eestimatedReady\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"X\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x03\x12\f\n" +
	"\bAPPROVED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x95\x03\n" +
	"\x0eStatusResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.cert_issuer.v1.StatusResponse.StatusR\x06status\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\fR\x0ecertificatePem\x12\x17\n" +
	"\akey_pem\x18\x03 \x01(\fR\x06keyPem\x12\x15\n" +
	"\x06ca_pem\x18\x04 \x01(\fR\x05caPem\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12,\n" +
	"\x12days_until_renewal\x18\a \x01(\x05R\x10daysUntilRenewal\"I\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04\"R\n" +
	"\fRenewRequest\x12%\n" +
	"\x0ecertificate_id\x18\x01 \x01(\tR\rcertificateId\x12\x1b\n" +
	"\tissuer_id\x18\x02 \x01(\tR\bissuerId\"m\n" +
	"\rRenewResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.cert_issuer.v1.StatusResponse.StatusR\x06status2\x9b\x02\n" +
	"\x12CertificateService\x12]\n" +
	"\x12RequestCertificate\x12\".cert_issuer.v1.CertificateRequest\x1a#.cert_issuer.v1.CertificateResponse\x12U\n" +
	"\x14GetCertificateStatus\x12\x1d.cert_issuer.v1.StatusRequest\x1a\x1e.cert_issuer.v1.StatusResponse\x12O\n" +
	"\x10RenewCertificate\x12\x1c.cert_issuer.v1.RenewRequest\x1a\x1d.cert_issuer.v1.RenewResponseB?Z=github.com/mdv-pochta/cert-system/proto/cert_issuer/v1;certv1b\x06proto3"

var (
	file_proto_cert_issuer_v1_certificate_service_proto_rawDescOnce sync.Once
	file_proto_cert_issuer_v1_certificate_service_proto_rawDescData []byte
)

func file_proto_cert_issuer_v1_certificate_service_proto_rawDescGZIP() []byte {
	file_proto_cert_issuer_v1_certificate_service_proto_rawDescOnce.Do(func() {
		file_proto_cert_issuer_v1_certificate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cert_issuer_v1_certificate_service_proto_rawDesc), len(file_proto_cert_issuer_v1_certificate_service_proto_rawDesc)))
	})
	return file_proto_cert_issuer_v1_certificate_service_proto_rawDescData
}

var file_proto_cert_issuer_v1_certificate_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_cert_issuer_v1_certificate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_cert_issuer_v1_certificate_service_proto_goTypes = []any{
	(CertificateRequest_RequestType)(0), // 0: cert_issuer.v1.CertificateRequest.RequestType
	(CertificateResponse_Status)(0),     // 1: cert_issuer.v1.CertificateResponse.Status
	(StatusResponse_Status)(0),          // 2: cert_issuer.v1.StatusResponse.Status
	(*CertificateRequest)(nil),          // 3: cert_issuer.v1.CertificateRequest
	(*CertificateResponse)(nil),         // 4: cert_issuer.v1.CertificateResponse
	(*StatusRequest)(nil),               // 5: cert_issuer.v1.StatusRequest
	(*StatusResponse)(nil),              // 6: cert_issuer.v1.StatusResponse
	(*RenewRequest)(nil),                // 7: cert_issuer.v1.RenewRequest
	(*RenewResponse)(nil),               // 8: cert_issuer.v1.RenewResponse
	(*timestamp.Timestamp)(nil),         // 9: google.protobuf.Timestamp
}
var file_proto_cert_issuer_v1_certificate_service_proto_depIdxs = []int32{
	0,  // 0: cert_issuer.v1.CertificateRequest.type:type_name -> cert_issuer.v1.CertificateRequest.RequestType
	1,  // 1: cert_issuer.v1.CertificateResponse.status:type_name -> cert_issuer.v1.CertificateResponse.Status
	9,  // 2: cert_issuer.v1.CertificateResponse.estimated_ready:type_name -> google.protobuf.Timestamp
	2,  // 3: cert_issuer.v1.StatusResponse.status:type_name -> cert_issuer.v1.StatusResponse.Status
	9,  // 4: cert_issuer.v1.StatusResponse.not_before:type_name -> google.protobuf.Timestamp
	9,  // 5: cert_issuer.v1.StatusResponse.not_after:type_name -> google.protobuf.Timestamp
	2,  // 6: cert_issuer.v1.RenewResponse.status:type_name -> cert_issuer.v1.StatusResponse.Status
	3,  // 7: cert_issuer.v1.CertificateService.RequestCertificate:input_type -> cert_issuer.v1.CertificateRequest
	5,  // 8: cert_issuer.v1.CertificateService.GetCertificateStatus:input_type -> cert_issuer.v1.StatusRequest
	7,  // 9: cert_issuer.v1.CertificateService.RenewCertificate:input_type -> cert_issuer.v1.RenewRequest
	4,  // 10: cert_issuer.v1.CertificateService.RequestCertificate:output_type -> cert_issuer.v1.CertificateResponse
	6,  // 11: cert_issuer.v1.CertificateService.GetCertificateStatus:output_type -> cert_issuer.v1.StatusResponse
	8,  // 12: cert_issuer.v1.CertificateService.RenewCertificate:output_type -> cert_issuer.v1.RenewResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_cert_issuer_v1_certificate_service_proto_init() }
func file_proto_cert_issuer_v1_certificate_service_proto_init() {
	if File_proto_cert_issuer_v1_certificate_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cert_issuer_v1_certificate_service_proto_rawDesc), len(file_proto_cert_issuer_v1_certificate_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cert_issuer_v1_certificate_service_proto_goTypes,
		DependencyIndexes: file_proto_cert_issuer_v1_certificate_service_proto_depIdxs,
		EnumInfos:         file_proto_cert_issuer_v1_certificate_service_proto_enumTypes,
		MessageInfos:      file_proto_cert_issuer_v1_certificate_service_proto_msgTypes,
	}.Build()
	File_proto_cert_issuer_v1_certificate_service_proto = out.File
	file_proto_cert_issuer_v1_certificate_service_proto_goTypes = nil
	file_proto_cert_issuer_v1_certificate_service_proto_depIdxs = nil
}
